机翻
SlimefunGuguProject/MetalWorks pull request #1
Opened 2022-08-29 02:19 UTC by buiawpkgew1

有地方不对 建议改

2022-08-29 22:22 UTC, ybw0014 requested changes
不要机翻，就这点东西
工具的命名格式应该与原版MC统一
子分类名称中间可以加 -

2022-08-29 22:22 UTC, ybw0014 commented on src/main/java/me/jasperchasetoq/metalworks/MetalWorksItems.java
> +    public static final NestedItemGroup MetalWorks_General = new NestedItemGroup(new NamespacedKey(MetalWorks.getInstance(), "METALWORKS_GENERAL"), new CustomItemStack(Material.ANVIL, "&f金属工作"));
金属工艺

2022-08-29 22:22 UTC, ybw0014 commented on src/main/java/me/jasperchasetoq/metalworks/MetalWorksItems.java
> +    public static final SubItemGroup Leggings = new SubItemGroup(new NamespacedKey(MetalWorks.getInstance(), "LEGGINGS"), MetalWorks_General, new CustomItemStack(Material.DIAMOND_LEGGINGS, "&f金属制品金属制
重复

2022-08-29 22:22 UTC, ybw0014 commented on src/main/java/me/jasperchasetoq/metalworks/MetalWorksItems.java
> +    public static final SubItemGroup Shields = new SubItemGroup(new NamespacedKey(MetalWorks.getInstance(), "SHIELDS"), MetalWorks_General, new CustomItemStack(Material.SHIELD, "&f金属制品护罩"));
盾

2022-08-29 22:22 UTC, ybw0014 commented on src/main/java/me/jasperchasetoq/metalworks/MetalWorksItems.java
> +    public static final SlimefunItemStack JC_GOLD_4K_BOW = new SlimefunItemStack("JC_GOLD_4K_BOW", Material.BOW, "&金色蝴蝶结&7(4克拉)");
?

2022-08-30 03:59 UTC, buiawpkgew1 commented on src/main/java/me/jasperchasetoq/metalworks/MetalWorksItems.java
> +    public static final SlimefunItemStack JC_GOLD_4K_BOW = new SlimefunItemStack("JC_GOLD_4K_BOW", Material.BOW, "&金色蝴蝶结&7(4克拉)");
机翻的

2022-08-30 04:03 UTC, buiawpkgew1 commented on src/main/java/me/jasperchasetoq/metalworks/MetalWorksItems.java
> +    public static final SlimefunItemStack JC_GOLD_4K_BOW = new SlimefunItemStack("JC_GOLD_4K_BOW", Material.BOW, "&金色蝴蝶结&7(4克拉)");
> ?

要怎么改？

2022-09-27 07:16 UTC, closed without merging